version: '3.1'
 
services:
 
  main:
    image: devday/jenkins
    ports:
      - 8800:8080
      - 50000:50000
    
    volumes:
      - /tmp/codecomp-sessions:/work/sessions

    secrets:
      - jenkins-user
      - jenkins-pass
 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
